from building import *

# The set of source files associated with this SConscript file.
src = Split('''
quantization_util.cc
''')
cwd = GetCurrentDir()

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('lite', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))


Return('group')
