from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cc')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Flatbuffers', src, depend = ['BSP_USING_TFLITE'], CPPPATH = CPPPATH)

Return('group')
