import os
from os.path import join as opjoin
from building import *

# The set of source files associated with this SConscript file.
src =  []
cwd = GetCurrentDir()
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflite = os.path.join(packages, f)
        cmsis = opjoin(tflite, 'tflite/micro/tools/')
        break

CPPPATH = [cwd, cmsis]


group = DefineGroup('lite', src, depend = ['PKG_USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH)

Return('group')