from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cc')
CPPPATH = [cwd]

group = DefineGroup('lite', src, depend = ['PKG_USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH)

Return('group')
