from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src = []

if GetDepend(['BSP_USING_TFLITE_AUDIO_EXAMPLE']):
    src += Split('audio_main.cc') 
else:
    src += Split('main.cc')



group = DefineGroup('application', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
