from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src = []

if GetDepend(['PKG_USING_TENSORFLOWLITEMICRO_AUDIO_EXAMPLE']):
    src += Split('audio_main.cc') 

group = DefineGroup('application', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
