from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('TFLMICRO', src, depend = ['TFLMICRO_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
