import os
from building import *

# The set of source files associated with this SConscript file.
src =  Glob('*.cc')
cwd = GetCurrentDir()
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflite = os.path.join(packages, f)
        break

CPPPATH = [cwd, tflite]

group = DefineGroup('lite', src, depend = ['PKG_USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH)

Return('group')