import os
from building import *

# The set of source files associated with this SConscript file.
src =  []
cwd = GetCurrentDir()
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflite = os.path.join(packages, f)
        break

CPPPATH = [cwd, tflite]

if GetDepend('PKG_USING_TENSORFLOWLITEMICRO_REFERENCE'):
    src += Glob('*.cc') + Glob('reference/*.cc')

if GetDepend('PKG_USING_TENSORFLOWLITEMICRO_CMSISNN'):
    src += Glob('*.cc') + Glob('cmsis-nn/*.cc')


group = DefineGroup('lite', src, depend = ['PKG_USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH)

Return('group')