from building import *

# The set of source files associated with this SConscript file.
src = Split('''
all_ops_resolver.cc
debug_log.cc
memory_helpers.cc
micro_allocator.cc
micro_error_reporter.cc
micro_interpreter.cc
micro_optional_debug_tools.cc
micro_string.cc
micro_time.cc
micro_utils.cc
recording_micro_allocator.cc
recording_simple_memory_allocator.cc
simple_memory_allocator.cc
test_helpers.cc
''') + Glob('kernels/*.cc') + Glob('memory_planner/*.cc') + Glob('testing/*.cc') + Glob('examples/micro_speech/*.cc') \
+ Glob('examples/micro_speech/micro_features/*.cc')  # + Glob('examples/micro_speech/simple_features/*.cc')

cwd = GetCurrentDir()

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('lite', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
