import rtconfig
from building import *

cwd  = GetCurrentDir()
src  = Glob('*.cc')

#.
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflm_pkg = os.path.join(packages, f)
        break

CPPPATH = [tflm_pkg]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
